export const SPECIALTY_OPTIONS = [
  "Frontend",
  "Backend",
  "Full Stack",
  "Smart Contracts",
  "DevOps",
  "UI/UX",
  "Data Science",
  "AI/ML",
  "QA",
  "Security",
  "Product Management",
  "Community",
  "Technical Writing",
  "Documentation",
  "Marketing",
  "Growth",
  "DAO Operations",
  "Treasury",
  "Legal",
  "Research",
  "Partnerships",
  "Content",
  "Social Media",
  "Analytics",
  "Mobile",
  "Cloud",
  "Protocol Design",
  "Governance",
  "Translation",
  "Video",
];